timings: true
database:
  host: localhost
  port: 27017
  username: admin
  password: odEylO2Xeh84JLfcu5
  database: hcf
staff:
  launch_velocity: 5.0
  chat_slow: 10
deathban:
  times:
    default: 7200
    commodore: 5400
    premier: 4500
    grandmaster: 2700
    beta: 1800
SERVER: first
hubs:
  lobby: 'localhost:25467'
  lobby2: 'localhost:25468'
deathban:
  times:
    default: 120
    commodore: 90
    premier: 75
    grandmaster: 45
    beta: 30
gadgets:
  launcher:
    enabled: true
    slot: 1
    item: COMPASS:-1
    name: "&4Launcher"
    lore:
      - "&7Launches you towards the"
      - "&7location you are facing."
  carpet:
    enabled: true
    slot: 6
    item: CARPET:14
    name: "&6Carpet"
    lore:
      - "&7I can see clearly now"
      - "&7that the rain is gone."
  vanish:
    enabled: true
    slot: 8
    item: INK_SACK:1
    name: "&6Vanish"
    lore:
      - "&7Toggles your player vanish."
    item-on: INK_SACK:10
  teleporter:
    enabled: true
    slot: 4
    item: EYE_OF_ENDER:-1
    name: "&6Random Teleporter"
    lore:
      - "&7Teleports you to a random player."
  freezer:
    enabled: true
    slot: 2
    item: BLAZE_ROD:-1
    name: "&2Freeze"
    lore:
      - "&7Toggles freeze for the clicked player."
  examine:
    enabled: true
    slot: 9
    item: BOOK:-1
    name: "&bExamine"
    lore:
      - "&7Inspects the inventory of the player that was clicked."