database:
  host: localhost
  port: 27017
  username: admin
  password: odEylO2Xeh84JLfcu5
  database: hcf
logout:
  time: 10
staff:
  launch_velocity: 5.0
timers:
  pvp:
    time: 1800
deathban:
  times:
    default: 7200
glass-protected-regions:
   - 'test1'
   - 'test2'
   - 'test3'
   - 'test4'
spawn-mobs: false
SERVER: first
hubs:
  lobby: 'localhost:25467'
  lobby2: 'localhost:25468'
deathban:
  times:
    default: 120
    brigadier: 90
    commodore: 75
    grandmaster: 60
gadgets:
  launcher:
    enabled: true
    slot: 1
    item: COMPASS:-1
    name: "&4Launcher"
    lore:
      - "&7Launches you towards the"
      - "&7location you are facing."
  random-teleport:
    enabled: true
    slot: 2
    item: EYE_OF_ENDER:-1
    name: "&cRandom Teleport"
    lore:
      - "&7Teleports you to a random player."
  vanish:
    enabled: true
    slot: 3
    item: INK_SACK:10
    name: "&6Vanish"
    lore:
      - "&7Toggles your player vanish."
    item-off: INK_SACK:8
  reports:
    enabled: true
    slot: 4
    item: PAPER:-1
    name: "&eReports GUI"
    lore:
      - "&7Opens the Reports GUI."
  freezer:
    enabled: true
    slot: 6
    item: BLAZE_ROD:-1
    name: "&2Freeze"
    lore:
      - "&7Toggles freeze for the clicked player."
  clicker:
    enabled: true
    slot: 7
    item: WATCH:-1
    name: "&3CPS Test"
    lore:
      - "&7Runs a click per second test on"
      - "&7the player that was clicked."
  examine:
    enabled: true
    slot: 8
    item: CHEST:-1
    name: "&bExamine"
    lore:
      - "&7Inspects the inventory of the player that was clicked."
  follow:
    enabled: true
    slot: 9
    item: LEASH:-1
    name: "&9Follow"
    lore:
      - "&7Mounts the player that was clicked."