database:
  host: localhost
  port: 27017
  username: admin
  password: odEylO2Xeh84JLfcu5
  database: hcf
logout:
  time: 10
staff:
  launch_velocity: 5.0
timers:
  pvp:
    time: 1800
deathban:
  times:
    default: 7200
glass-protected-regions:
   - 'test1'
   - 'test2'
   - 'test3'
   - 'test4'
spawn-mobs: false
SERVER: first
hubs:
  lobby: 'localhost:25467'
  lobby2: 'localhost:25468'
deathban:
  times:
    default: 120
    brigadier: 90
    commodore: 75
    grandmaster: 60